import time
import pyautogui
import clipboard
import pyscreenshot
from pydoc import classname
from operator import index
from selenium import webdriver
from dados.dewalt.listaProdutosDewalt import listaProdutosDewalt

# Pasta Bloco1 168 = ok #
# Pasta Bloco2 181 = ok #
# Pasta Bloco3 155 = ok #
# Pasta Bloco4 157 = ok #
# Pasta Bloco5 182 = ok #
# Pasta Bloco6 162 = ... #

item = 1
while item <= 162:
    nomeArquivo = ''
    # inicar o app de merge pdf #
    pyautogui.moveTo(1131, 1063)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(5)       
    pyautogui.press('esc')
    time.sleep(0.4)
    pyautogui.moveTo(141, 487)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.moveTo(1036, 201)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.moveTo(1096, 258)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    # busca PDF para mergear #
    pyautogui.press('f4')
    time.sleep(0.2)
    pyautogui.hotkey('ctrl', 'a')
    time.sleep(0.2)
    pyautogui.press('backspace')
    time.sleep(0.2)
    pyautogui.write('C:/Users/pedro.holanda/Desktop/Rocfer/PDF/Dewalt/Download-Dewalt/Bloco6')
    time.sleep(0.2)
    pyautogui.press('enter')
    time.sleep(0.2)
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('down')
    time.sleep(0.2)
    pyautogui.press('f2')
    time.sleep(0.2)
    pyautogui.hotkey('ctrl', 'c')
    time.sleep(0.2)
    nomeArquivo = clipboard.paste()  
    time.sleep(0.4)  
    pyautogui.press('enter')
    time.sleep(0.4)
    pyautogui.press('enter')
    time.sleep(0.4)
    pyautogui.moveTo(870, 604)
    time.sleep(0.4)
    pyautogui.click(button='right') 
    time.sleep(0.4)
    pyautogui.press('down')
    pyautogui.press('down')
    pyautogui.press('enter')
    pyautogui.press('down')        
    pyautogui.press('down')        
    pyautogui.press('down')        
    pyautogui.press('down')        
    pyautogui.press('down')
    pyautogui.press('enter')        
    pyautogui.hotkey('ctrl', 'a')
    time.sleep(0.4)
    pyautogui.press('enter')
    time.sleep(0.4)
    pyautogui.moveTo(1535, 200)
    time.sleep(0.4)
    pyautogui.click()
    time.sleep(3)
    pyautogui.hotkey('ctrl', 's')
    time.sleep(2)
    pyautogui.press('f4')
    time.sleep(0.2)
    pyautogui.hotkey('ctrl', 'a')
    time.sleep(0.2)                       
    pyautogui.press('backspace')
    time.sleep(0.2)
    pyautogui.write('C:/Users/pedro.holanda/Desktop/Rocfer/PDF/Dewalt')
    time.sleep(0.2)
    pyautogui.press('enter')
    time.sleep(0.2)  
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    time.sleep(0.7)
    pyautogui.write(nomeArquivo)
    time.sleep(0.4)
    pyautogui.press('enter')
    time.sleep(2)
    pyautogui.hotkey('alt', 'f4')
    time.sleep(0.4)
    # deleta o que sobra na pasta origem #
    pyautogui.hotkey('win', 'd')
    time.sleep(0.3)
    pyautogui.hotkey('win', 'r')
    time.sleep(0.4)
    pyautogui.write('C:/Users/pedro.holanda/Desktop/Rocfer/PDF/Dewalt/Download-Dewalt/Bloco6')
    time.sleep(0.4)
    pyautogui.press('enter')
    time.sleep(1)
    pyautogui.press('down')
    time.sleep(0.5)
    pyautogui.write(nomeArquivo)
    time.sleep(0.5)    
    pyautogui.press('delete')
    time.sleep(0.5)
    pyautogui.hotkey('alt', 'f4')
    time.sleep(0.2)
    item = item+1            