import time
import pyautogui
import clipboard
import pyscreenshot
from pydoc import classname
from operator import index
from selenium import webdriver
from dados.dewalt.listaProdutosDewalt import listaProdutosDewalt

# instancia o google chrome #
navegador = webdriver.Chrome()
link = 'https://posvenda.telecontrol.com.br/assist/externos/login_posvenda_new.php'
navegador.get(url=link)

x, y = pyautogui.position()
print(x, y)

# realiza o login #
email = 'carlos@rocfer.com.br'
senha = 'bife4112@'   
campo_email = navegador.find_element('xpath', '//*[@id="login"]')
campo_email.send_keys(email)
campo_senha = navegador.find_element('xpath', '//*[@id="senha"]')
campo_senha.send_keys(senha)
navegador.find_element('xpath', '//*[@id="btnAcao"]').click()

# faz rota sistemica dewalt #
navegador.find_element('xpath', '/html/body/center/div[2]/div/ul/li[1]/a').click()
time.sleep(1)
navegador.find_element('xpath', '//*[@id="menu_inicial"]/div/div/ul/li[8]/a').click()
time.sleep(1)

# salva PDF #
for item in listaProdutosDewalt.listaProdutosBloco1_200:
    existeVistaExplodida = ''
    # fazer rota sistemica para vista #
    pyautogui.hotkey('ctrl', 'r')
    time.sleep(4)
    navegador.find_element('xpath', '/html/body/center/table[1]/tbody/tr[5]/td[1]/a').click()
    time.sleep(3)
    pyautogui.moveTo(778, 394, 1)
    time.sleep(1)
    pyautogui.click()
    time.sleep(1)
    pyautogui.write(item)
    time.sleep(1)
    pyautogui.press('enter')
    time.sleep(5)
    pyautogui.doubleClick(920, 646)
    time.sleep(1)
    pyautogui.hotkey('ctrl', 'c')
    time.sleep(1)
    existeVistaExplodida = clipboard.paste()
    time.sleep(1)
    if (existeVistaExplodida == 'Vista ' or existeVistaExplodida == 'Informativo '):
        # salva PDF do telecontrol #
        pyautogui.moveTo(958, 567, 1)
        time.sleep(1)
        pyautogui.click()
        time.sleep(15)
        pyautogui.hotkey('ctrl', 'w')
        time.sleep(1)
        pyautogui.hotkey('win', 'd')
        time.sleep(1)
        pyautogui.hotkey('win', 'r')
        time.sleep(1)
        pyautogui.write('Downloads')
        time.sleep(1)
        pyautogui.press('enter')
        time.sleep(1)
        pyautogui.moveTo(637, 178, 1)
        time.sleep(1)
        pyautogui.click(button='right') 
        time.sleep(1)
        pyautogui.moveTo(703, 540, 1)
        time.sleep(1)
        pyautogui.click()
        time.sleep(1)
        pyautogui.press('down')
        time.sleep(1)
        pyautogui.press('down')
        time.sleep(1)
        pyautogui.press('down')
        time.sleep(1)
        pyautogui.press('down')
        time.sleep(1)
        pyautogui.press('down')
        time.sleep(1)
        pyautogui.press('enter')
        time.sleep(1)
        pyautogui.press('enter')
        time.sleep(1)
        pyautogui.hotkey('ctrl', 'w')
        time.sleep(1)
        pyautogui.press('delete')
        time.sleep(1)
        pyautogui.hotkey('ctrl', 'w')
        time.sleep(1)
        # inicar o app de merge pdf #
        pyautogui.moveTo(1189, 1053, 1)
        pyautogui.click()
        time.sleep(3)
        pyautogui.press('esc')
        time.sleep(1)
        pyautogui.moveTo(141, 487, 1)
        time.sleep(1)
        pyautogui.click()
        time.sleep(1)
        pyautogui.moveTo(1036, 201, 1)
        time.sleep(1)
        pyautogui.click()
        time.sleep(1)
        pyautogui.moveTo(1096, 258, 1)
        time.sleep(1)
        pyautogui.click()
        time.sleep(1)
        # busca PDF para mergear #
        pyautogui.press('f4')
        time.sleep(1)
        pyautogui.hotkey('ctrl', 'a')
        time.sleep(1)
        pyautogui.press('backspace')
        time.sleep(1)
        pyautogui.write('C:/Users/pedro.holanda/Downloads')
        time.sleep(1)
        pyautogui.press('enter')
        time.sleep(1)
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.press('down')
        time.sleep(1)
        pyautogui.press('enter')
        time.sleep(1)
        pyautogui.moveTo(870, 604, 1)
        time.sleep(1)
        pyautogui.click()
        time.sleep(1)
        pyautogui.press('down')
        time.sleep(1)
        pyautogui.press('down')
        time.sleep(1)
        pyautogui.press('enter')
        time.sleep(1)
        pyautogui.press('down')
        time.sleep(1)        
        pyautogui.press('down')
        time.sleep(1)        
        pyautogui.press('down')
        time.sleep(1)        
        pyautogui.press('down')
        time.sleep(1)        
        pyautogui.press('down')
        time.sleep(1)
        pyautogui.press('enter')
        time.sleep(1)        
        pyautogui.hotkey('ctrl', 'a')
        time.sleep(1)
        pyautogui.press('enter')
        time.sleep(1)
        pyautogui.moveTo(1535, 200, 1)
        time.sleep(3)
        pyautogui.click()
        time.sleep(1)
        # salva PDF na pasta correta #
        pyautogui.hotkey('ctrl', 's')
        time.sleep(1)
        pyautogui.press('f4')
        time.sleep(1)
        pyautogui.hotkey('ctrl', 'a')
        time.sleep(1)                       
        pyautogui.press('backspace')
        time.sleep(1)
        pyautogui.write('C:/Users/pedro.holanda/Desktop/Rocfer/PDF/Dewalt/Download-Dewalt')
        time.sleep(1)
        pyautogui.press('enter')
        time.sleep(1)
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.write(item)
        time.sleep(1)
        pyautogui.press('enter')
        time.sleep(2)
        pyautogui.hotkey('alt', 'f4')
        time.sleep(1)
        # deleta o que sobra na pasta downloads #
        pyautogui.hotkey('win', 'd')
        time.sleep(1)
        pyautogui.hotkey('win', 'r')
        time.sleep(1)
        pyautogui.write('C:/Users/pedro.holanda/Downloads')
        time.sleep(1)
        pyautogui.press('enter')
        time.sleep(1)
        pyautogui.press('down')
        time.sleep(1)
        pyautogui.hotkey('ctrl', 'a')
        time.sleep(1)
        pyautogui.press('delete')
        time.sleep(1)
        pyautogui.hotkey('alt', 'f4')
        time.sleep(1)   
        # retorna pro google #     
        pyautogui.moveTo(1254, 1056, 1)
        pyautogui.click()
        time.sleep(1)
        pyautogui.hotkey('ctrl', '1')
        pyautogui.moveTo(1900, 1009, 1)
        pyautogui.click()
        time.sleep(1)        
    else:
        image = pyscreenshot.grab()  
        image.save(f'{item}.png')
        pyautogui.hotkey('ctrl', 'w')
        time.sleep(1)
        pyautogui.hotkey('ctrl', '1')
        time.sleep(1)
        
# ao finalizar o salvar PDF ele fecha o chrome
navegador.quit()